### ISSUE TITLE
Sodium Plus 2.2.3 contains outdated mods

### ISSUE THREAD

**Issue by yellowwinner** [NoSadBeHappy/sodiumplus#10]
The current version of the modpack, 2.2.3 for Minecraft 1.20.1, has a couple mods that aren't working but have updated versions. Most notably Xaero's Minimap which can be manually be updated in Prism Launcher as a temp fix.

**Comment by NoSadBeHappy** [comment]
The next version will fix this issue. I am on vacation right now, so if @RedstoneWizard08 doesn't fix it, I will get to it early next week.

**Comment by RedstoneWizard08** [comment]
Yeah sorry I've been busy with another project for a while. I'll get on this tomorrow. Sorry for the delay!

**Comment by NoSadBeHappy** [comment]
This should be fixed in the most recent versions of the modpack. If not, you can make a new issue. Thanks for helping!
