### ISSUE TITLE
Sliders can go into the negatives and go above the normal default limit.

### ISSUE THREAD

**Issue by realRox** [NoSadBeHappy/sodiumplus#11]
I don't know if this is a bug or a feature but it's really annoying. If it is a feature is there a way to toggle/turn it off? It works on any slider in video, audio, and even mouse settings.
![image](https://github.com/NoSadBeHappy/sodiumplus/assets/133183961/5f97e86b-2f19-44f2-a6c1-4fba6deb3a9e)
![image](https://github.com/NoSadBeHappy/sodiumplus/assets/133183961/c5b4b974-5193-4397-a794-dd669e000696)

**Comment by NoSadBeHappy** [comment]
This is due to the mod slyde. If you don't like it, you can remove the mod.

**Comment by realRox** [comment]
Thank you :)
