### ISSUE TITLE
60FPS only in inventory?

### ISSUE THREAD

**Issue by SillyPupMommy** [NoSadBeHappy/sodiumplus#12]
Hi, tried to reach you at the attached discord but it didn't allow me to enter. I'm having an issue with the modpack, going into the inventory locks my fps to 60 when everything outside of the inventory is 144. Does anyone know what mod/setting could be doing this? (V-sync is off btw)

**Comment by NoSadBeHappy** [comment]
This is most likely due to dynamic fps. You can change the settings in mod menu. Also, what was the issue with the discord? I would like to get that fixed.

**Comment by SillyPupMommy** [comment]
I played around with Dynamic FPS and nothing changed, may be a problem with REI, maybe the loading of all the icons tanks performance or smth but idk. When I tried joining the server on Modrinth the server just refuses to load after accepting the rules and stuff. Probably a discord issue but idk, never had problems with community servers.

**Comment by NoSadBeHappy** [comment]
Try again with the discord, I have updated the invite link. We can continue troubleshooting on there.

**Comment by NoSadBeHappy** [comment]
Have you fegured this issue out @SillyPupMommy, if so could you let me know what it is so I can fix it? If not let me know too and I will try to look more into this.

**Comment by SillyPupMommy** [comment]
Oh yeah! Sorry, forgot about the thread cuz of life :P. It turned out it was the REI loading way too many block icons. Lowering the amount of blocks displayed and size of the window helped and my FPS issues went away completely :3

**Comment by NoSadBeHappy** [comment]
Oh okay thanks, no problem.
