### ISSUE TITLE
Please stop hiding the donation button in Sodium's video setting screen

### ISSUE THREAD

**Issue by jellysquid3** [NoSadBeHappy/sodiumplus#13]
As it appears [here](https://github.com/NoSadBeHappy/sodiumplus/blob/main/config/sodium-options.json#L23), you are shipping a config file which disables the prompt for a user to consider donating to our project. Please remove this config entry override so that users are shown the prompt again.

This is a single button in the video settings screen and should not bother anyone. If the user is bothered, they can click a single button (right next to our prompt) and permanently dismiss it.

**Comment by NoSadBeHappy** [comment]
Sorry about this. I understand that you want this enabled. I will fix the issue and release a new version by the end of the day.

**Comment by NoSadBeHappy** [comment]
I have fixed this issue in v.2.2.6. Thank you for reaching out, and I am always happy to help. Honestly this modpack started with me wanting all my mods together and I didn't know that so many people would use it. So I fully understand that you want the donate button visable.

**Comment by jellysquid3** [comment]
It is no issue. I had just assumed that you had just copied the config file from a game directory which had option already hidden, since it is pretty easy to do. Thanks for changing it!

**Comment by NoSadBeHappy** [comment]
Yep thats what happened. No problem at all.
