### ISSUE TITLE
chunks 

### ISSUE THREAD

**Issue by antihak123** [NoSadBeHappy/sodiumplus#15]
Hello please tell me what to do, my chunks don't want to load
![huge_2023-08-16_18 50 30](https://github.com/NoSadBeHappy/sodiumplus/assets/101661556/d7f0cd99-3e68-4cb6-a74b-dd957def3adc)

**Comment by RedstoneWizard08** [comment]
I've seen this before, it may be a desync between the client and server packets (they don't want to send them to each other anymore). Try reloading your world and/or restarting your game.
