### ISSUE TITLE
Modloader switch appears to be slower.

### ISSUE THREAD

**Issue by yellowwinner** [NoSadBeHappy/sodiumplus#2]
I was doing an update on this pack and I noticed the newest version was running on Quilt. To be honest I've been out of the greater moding community for a while so I had to do some research to figure out what this was but long story short I did some quick testing and despite the changelog claiming "Sense quilt is faster, and this is a optimazation pack, I am working on moving to only using quilt." I put 1.4.0 up against 1.4.2 with a timer on a world to see which would load faster along with consistently better FPS and Fabric definitely won the battle. I don't know about the LoD version but definitely worth checking out if the normal version isn't preforming as well with the new modloader. Also I hope to see an update to 1.19.3 soon :)

**Comment by RedstoneWizard08** [comment]
Firstly, the quilt version is in beta, so yeah, it's probably slower right now.

We're working on a 1.19.3 update, and it will be out hopefully very soon!

Thanks for your concern!

**Comment by RedstoneWizard08** [comment]
@yellowwinner BTW, the 1.19.3 update is now out!
