### ISSUE TITLE
Crashing upon opening mod menu

### ISSUE THREAD

**Issue by GogiBoy102** [NoSadBeHappy/sodiumplus#20]
Whenever i click on the mod menu it opens it and crashes. the crash report is                                                                                
`#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fae8e2ba628, pid=12226, tid=12227
#
# JRE version: Java(TM) SE Runtime Environment (17.0.8+9) (build 17.0.8+9-LTS-211)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.8+9-LTS-211, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [iris_dri.so+0x134628]
#
# Core dump will be written. Default location: Core dumps may be processed with "/lib/systemd/systemd-coredump %P %u %g %s %t 9223372036854775808 %h" (or dumping to /home/jeebak/Desktop/UltimMC/instances/Sodium Plus 2.2.8-2/.minecraft/core.12226)
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -javaagent:/home/jeebak/Desktop/UltimMC/injectors/authlib-injector-1.2.3.jar=http://localhost:34133 -Xms512m -Xmx1024m -Duser.language=en -Djava.library.path=/home/jeebak/Desktop/UltimMC/instances/Sodium Plus 2.2.8-2/natives org.multimc.EntryPoint

Host: 12th Gen Intel(R) Core(TM) i5-1235U, 12 cores, 7G, Linux Mint 21.2 Victoria
Time: Thu Sep 14 16:48:14 2023 IST elapsed time: 36.224235 seconds (0d 0h 0m 36s)`

**Comment by GogiBoy102** [comment]
After i removed and added each mod i found that removing Zoomify-2.11.0 seemed to solve the problem. So for now as a temporary solution removing Zoomify-2.11.0 seems to be the best option for know. I am requesting a proper solution.

**Comment by GogiBoy102** [comment]
After searching for a bit I found that this problem can be solved by updating the YACL to the newest fabric release meaning it is possible to have zoomify again. I request the Dev to please update the YACL which comes with the pack to the newest fabric release.

**Comment by NoSadBeHappy** [comment]
Thanks for your report, your right I need to update the pack, I've been quite busy recently. I will update sodium plus within the next couple days.

**Comment by GogiBoy102** [comment]
Thanks
