### ISSUE TITLE
Missing calc mod?

### ISSUE THREAD

**Issue by Josephloang** [NoSadBeHappy/sodiumplus#22]
After I grabbed the most recent beta version, I noticed that calc mod was missing. It didn't strike me as a significant problem, but I wasn't entirely certain whether this omission was deliberate or not. I find the mod to be quite handy!

**Comment by NoSadBeHappy** [comment]
_oops, no that is not intentional. I will fix this in the bug fix release in a couple days, thanks for the report._

**Comment by RedstoneWizard08** [comment]
Fixed in commit #9f9815a
