### ISSUE TITLE
Clicking on Video Settings lead to crash

### ISSUE THREAD

**Issue by Nurruddin** [NoSadBeHappy/sodiumplus#23]
Installed via Modrinth
This first happened in--world, but attempting from the menu also crashes the game.
Here's the log file:
https://mclo.gs/4wvQRO0

**Comment by RedstoneWizard08** [comment]
@NoSadBeHappy it's a problem with slyde, we gotta fix that xD

**Comment by RedstoneWizard08** [comment]
I'll work on it

**Comment by NoSadBeHappy** [comment]
Yeah im goingto put out a bugfix in a few days.

**Comment by nottucks** [comment]
Any updates on this? It's a big issue.

**Comment by NoSadBeHappy** [comment]
Sorry, I've been busy with school and haven't had time to update the pack.

**Comment by RedstoneWizard08** [comment]
Fixed in #9f9815a
