### ISSUE TITLE
[Mod/Feature request] Shulker box preview

### ISSUE THREAD

**Issue by leumasme** [NoSadBeHappy/sodiumplus#6]
![image](https://user-images.githubusercontent.com/29953391/236092348-fbc10570-ff17-4922-97a3-8446623da575.png)
This seems like a rather obvious Quality of Life feature and I've seen it provided by various mods before.

**Comment by NoSadBeHappy** [comment]
Good idea, I will add it in the next release. Right now, I broke packwiz, so it is kind of a pain to make a new release at the moment, so I will get to it in a little while. I will leave this open until I add it.

**Comment by RedstoneWizard08** [comment]
I'll fix Packwiz and add this over the weekend, @leumasme

**Comment by NoSadBeHappy** [comment]
Thank you @RedstoneWizard08

**Comment by RedstoneWizard08** [comment]
@leumasme This should be added as of 2.2.0 when it releases. Thanks for your feedback!
