### ISSUE TITLE
Minecraft is crashing after broke a sandblock.

### ISSUE THREAD

**Issue by ruwbine** [NoSadBeHappy/sodiumplus#8]
Minecraft crashes when falling blocks are processed by the type of sand, gravel, etc.

**Comment by NoSadBeHappy** [comment]
What version is this on?

**Comment by NoSadBeHappy** [comment]
Can you also please post the minecraft logs of when it crashes?

**Comment by NoSadBeHappy** [comment]
Ah nevermind, this issue is with the mod Continuity in v.2.2.1 I will look for a crash report for that mod. In the meantime, the issue can be solved by removing continuity until they update the mod to fix the issue. Once there is an update, I will release a new version of sodium plus.

**Comment by NoSadBeHappy** [comment]
Oh nevermind again, the actual issue is that I removed indium, as it was broken when I made the pack, which caused the issue with the sand because of continuity. Anyways, I am working on a release right now where the issue is fixed.

**Comment by NoSadBeHappy** [comment]
v.2.2.2 fixes this issue, thanks for your input!
